'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Net.Bertware.BukkitGUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bukkit_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bukkit_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FontCombo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FontCombo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property GUI_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUI_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUI_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ICSharpCode_SharpZipLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Interop_NATUPNPLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Interop_NATUPNPLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Jayrock_Json() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Jayrock_Json", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property JSONAPI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("JSONAPI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property JsonExSerializer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("JsonExSerializer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;Error while importing the Backup! Is this a valid file?&quot;&gt;Грешка при импортиране на Архива!Това валиден файл ли е?&lt;/text&gt;
        '''  &lt;text string=&quot;Import failed!&quot;&gt;Импортирането провалено!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the Backup!&quot;&gt;Грешка при импортиране на Архива!&lt;/text&gt;
        '''  &lt;text string=&quot;Export failed!&quot;&gt;Изнасянето неуспешно!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the backups!&quot;&gt;Грешка при Изнасяне на архивите!&lt;/text&gt;
        '''  &lt;text string=&quot;Backup cancelled&quot;&gt;А [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_bulgarian() As String
            Get
                Return ResourceManager.GetString("lang_bulgarian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;&quot;&gt;
        '''  &lt;/text&gt;
        '''  &lt;text string=&quot;Close&quot;&gt;Luk&lt;/text&gt;
        '''  &lt;text string=&quot;Copy&quot;&gt;Kopier&lt;/text&gt;
        '''  &lt;text string=&quot;Refresh&quot;&gt;
        '''    Genopfrisk
        '''  &lt;/text&gt;
        '''  &lt;text string=&quot;Browse console output&quot;&gt;
        '''    Gennemse konsol output
        '''  &lt;/text&gt;
        '''  &lt;text string=&quot;Description&quot;&gt;Beskrivelse&lt;/text&gt;
        '''  &lt;text string=&quot;IP&quot;&gt;IP&lt;/text&gt;
        '''  &lt;text string=&quot;Port&quot;&gt;Port&lt;/text&gt;
        '''  &lt;text string=&quot;Protocol&quot;&gt;Protokol&lt;/text&gt;
        '''  &lt;text string=&quot;Minecraft-server&quot;&gt;Minecraft-server&lt;/text&gt;
        '''  &lt;text string=&quot;Add&quot;&gt;Tilføj&lt;/tex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_danish() As String
            Get
                Return ResourceManager.GetString("lang_danish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;Algemeen&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;Spreek+(Ctrl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Op&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;De-op&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;Kicken&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;Verbannen&lt;/text&gt;
        '''  &lt;text string=&quot;Give...&quot;&gt;Geven...&lt;/text&gt;
        '''  &lt;text string=&quot;player_face.png&quot;&gt;player_face.png&lt;/text&gt;
        '''  &lt;text string=&quot;Send&quot;&gt;Verzenden&lt;/text&gt;
        '''  &lt;text string=&quot;Info&quot;&gt;Informatie&lt;/text&gt;
        '''  &lt;text string=&quot;000% [0000MB]&quot;&gt;000%25+%5b0000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_dutch() As String
            Get
                Return ResourceManager.GetString("lang_dutch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;Error while importing the Backup! Is this a valid file?&quot;&gt;Erreur pendant l&apos;importation de la sauvegarde! Est-elle valide?&lt;/text&gt;
        '''  &lt;text string=&quot;Import failed!&quot;&gt;Importation échouée&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the Backup!&quot;&gt;Erreur pendant l&apos;exportation de la sauvegarde&lt;/text&gt;
        '''  &lt;text string=&quot;Export failed!&quot;&gt;Exportation échouée&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the backups!&quot;&gt;Erreur pendant l&apos;exportation des sauvegardes&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_french() As String
            Get
                Return ResourceManager.GetString("lang_french", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;Allgemein&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;Say-Befehl+(Strgl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Op&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;De-op&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;Kick&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;Ban&lt;/text&gt;
        '''  &lt;text string=&quot;Give...&quot;&gt;Gebe...&lt;/text&gt;
        '''  &lt;text string=&quot;player_face.png&quot;&gt;player_face.png&lt;/text&gt;
        '''  &lt;text string=&quot;Send&quot;&gt;Senden&lt;/text&gt;
        '''  &lt;text string=&quot;Info&quot;&gt;Info&lt;/text&gt;
        '''  &lt;text string=&quot;000% [0000MB]&quot;&gt;000%25+%5b0000MB%5d&lt;/text&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_german() As String
            Get
                Return ResourceManager.GetString("lang_german", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;Error while importing the Backup! Is this a valid file?&quot;&gt;Errore nell&apos;importazione del Backup! E&apos; un file valido?&lt;/text&gt;
        '''  &lt;text string=&quot;Import failed!&quot;&gt;Importazione fallita!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the Backup!&quot;&gt;Errore nell&apos; esportazione del Backup!&lt;/text&gt;
        '''  &lt;text string=&quot;Export failed!&quot;&gt;Esportazione fallita!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the backups!&quot;&gt;Errore nell&apos;esportazione dei backup(s)!&lt;/text&gt;
        '''  &lt;text s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_italian() As String
            Get
                Return ResourceManager.GetString("lang_italian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;Latest stable:&quot;&gt;最新安定版%3a&lt;/text&gt;
        '''  &lt;text string=&quot;Latest beta:&quot;&gt;最新ベータ版%3a&lt;/text&gt;
        '''  &lt;text string=&quot;Latest dev:&quot;&gt;最新開発版%3a&lt;/text&gt;
        '''  &lt;text string=&quot;Site:&quot;&gt;Site%3a&lt;/text&gt;
        '''  &lt;text string=&quot;Loaded&quot;&gt;ロード完了&lt;/text&gt;
        '''  &lt;text string=&quot;plugins&quot;&gt;プラグイン&lt;/text&gt;
        '''  &lt;text string=&quot;Right click for options, double click for details.&quot;&gt;右クリックでオプション、ダブルクリックで詳細情報&lt;/text&gt;
        '''  &lt;text string=&quot;Double click for more information. Right Click for options.&quot;&gt;ダブルクリックで詳細情報、右クリックでオプション&lt;/text&gt;
        '''  &lt;text string=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_japanese() As String
            Get
                Return ResourceManager.GetString("lang_japanese", resourceCulture)
            End Get
        End Property
        Friend ReadOnly Property lang_korean() As String
            Get
                Return ResourceManager.GetString("lang_korean", resourceCulture)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;Ogólne&lt;/text&gt;
        '''  &lt;text string=&quot;Clear output&quot;&gt;Wyczyść+czat&lt;/text&gt;
        '''  &lt;text string=&quot;Auto Scroll&quot;&gt;Przewijanie&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;Stale pissz&lt;/text&gt;
        '''  &lt;text string=&quot;Name&quot;&gt;Nazwa&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Daj OPa&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;Zabierz OPa&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;Wyrzuć gracza&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;Zbanuj gracza&lt;/text&gt;
        '''  &lt;text string=&quot;Gamemode&quot;&gt;Tryb Gry&lt;/text&gt;
        '''  &lt;text string=&quot;Survival&quot;&gt;Przetrwanie&lt;/text&gt;
        '''  &lt;te [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_polish() As String
            Get
                Return ResourceManager.GetString("lang_polish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;General&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;Chat+Global+(Ctrl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Op&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;De-op&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;Kick&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;Ban&lt;/text&gt;
        '''  &lt;text string=&quot;Give...&quot;&gt;Ofera+item...&lt;/text&gt;
        '''  &lt;text string=&quot;player_face.png&quot;&gt;player_face.png&lt;/text&gt;
        '''  &lt;text string=&quot;Send&quot;&gt;Trimite&lt;/text&gt;
        '''  &lt;text string=&quot;Info&quot;&gt;Informatii&lt;/text&gt;
        '''  &lt;text string=&quot;000% [0000MB]&quot;&gt;000%25+%5b0000M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_romanian() As String
            Get
                Return ResourceManager.GetString("lang_romanian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;Главная&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;Сказать+(Ctrl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Сделать+Администратором&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;Убрать+из+Администраторов&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;Кик&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;Бан&lt;/text&gt;
        '''  &lt;text string=&quot;Give...&quot;&gt;Дать...&lt;/text&gt;
        '''  &lt;text string=&quot;player_face.png&quot;&gt;player_face.png&lt;/text&gt;
        '''  &lt;text string=&quot;Send&quot;&gt;Отправить&lt;/text&gt;
        '''  &lt;text string=&quot;Info&quot;&gt;Инфо&lt;/text&gt;
        '''  &lt;text string=&quot;000% [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_russian() As String
            Get
                Return ResourceManager.GetString("lang_russian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;通用&lt;/text&gt;
        '''  &lt;text string=&quot;Clear output&quot;&gt;清除输出&lt;/text&gt;
        '''  &lt;text string=&quot;Auto Scroll&quot;&gt;自动滚动&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;发言 (Ctrl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Name&quot;&gt;名称&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Op&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;取消OP&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;踢除&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;禁止&lt;/text&gt;
        '''  &lt;text string=&quot;Gamemode&quot;&gt;游戏模式&lt;/text&gt;
        '''  &lt;text string=&quot;Survival&quot;&gt;生存模式&lt;/text&gt;
        '''  &lt;text string=&quot;Creative&quot;&gt;创造模式&lt;/text&gt;
        '''  &lt;text string=&quot;Adventure&quot;&gt;冒险模式 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_simplifiedChinese() As String
            Get
                Return ResourceManager.GetString("lang_simplifiedChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;Error while importing the Backup! Is this a valid file?&quot;&gt;¡Error al importar la Copia de Seguridad! ¿Es el archivo correcto?&lt;/text&gt;
        '''  &lt;text string=&quot;Import failed!&quot;&gt;¡Error al Importar!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the Backup!&quot;&gt;¡Error al exportar la Copia de Seguridad!&lt;/text&gt;
        '''  &lt;text string=&quot;Export failed!&quot;&gt;¡Error al Exportar!&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the backups!&quot;&gt;¡Error al exportar las Copias de seguridad!&lt;/text&gt;
        '''  &lt;text strin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_spanish() As String
            Get
                Return ResourceManager.GetString("lang_spanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.0&quot;&gt;
        '''  &lt;text string=&quot;General&quot;&gt;通用&lt;/text&gt;
        '''  &lt;text string=&quot;Clear output&quot;&gt;清除輸出&lt;/text&gt;
        '''  &lt;text string=&quot;Auto Scroll&quot;&gt;自動滾動&lt;/text&gt;
        '''  &lt;text string=&quot;Say (Ctrl+S)&quot;&gt;發言 (Ctrl%2bS)&lt;/text&gt;
        '''  &lt;text string=&quot;Name&quot;&gt;名稱&lt;/text&gt;
        '''  &lt;text string=&quot;Op&quot;&gt;Op&lt;/text&gt;
        '''  &lt;text string=&quot;De-op&quot;&gt;取消OP&lt;/text&gt;
        '''  &lt;text string=&quot;Kick&quot;&gt;踢除&lt;/text&gt;
        '''  &lt;text string=&quot;Ban&quot;&gt;禁止&lt;/text&gt;
        '''  &lt;text string=&quot;Gamemode&quot;&gt;遊戲模式&lt;/text&gt;
        '''  &lt;text string=&quot;Survival&quot;&gt;生存模式&lt;/text&gt;
        '''  &lt;text string=&quot;Creative&quot;&gt;創造模式&lt;/text&gt;
        '''  &lt;text string=&quot;Adventure&quot;&gt;冒險模式 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_traditionalChinese() As String
            Get
                Return ResourceManager.GetString("lang_traditionalChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language version=&quot;1.1&quot; target=&quot;1.0.0.126&quot;&gt;
        '''  &lt;text string=&quot;Error while importing the Backup! Is this a valid file?&quot;&gt;Yedek dosyasını içe aktarırken hata çıktı ! Geçerli bir yedek alındığından emin misin?&lt;/text&gt;
        '''  &lt;text string=&quot;Import failed!&quot;&gt;İçe aktarma başarısız oldu :&apos;(&lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the Backup!&quot;&gt;
        '''    Yedek alırken bir hata çıktı !
        '''  &lt;/text&gt;
        '''  &lt;text string=&quot;Export failed!&quot;&gt;
        '''    Yedek alınamadı.
        '''  &lt;/text&gt;
        '''  &lt;text string=&quot;Error while exporting the backups!&quot;&gt;
        '''    Yed [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_turkish() As String
            Get
                Return ResourceManager.GetString("lang_turkish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Net_Bertware_Controls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Net_Bertware_Controls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Net_Bertware_Utilities_WMI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Net_Bertware_Utilities_WMI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_face() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_face", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound_connect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound_connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound_disconnect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound_severe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound_severe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound_warning() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound_warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spigot_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spigot_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Substrate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Substrate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vanilla_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vanilla_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property YamlUtility() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("YamlUtility", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
